# Generated by Django 5.2.3 on 2025-06-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='passport',
        ),
    ]
