# Generated by Django 5.2.3 on 2025-06-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('semi_lux', 'Полу-люкс'), ('lux', 'Люкс'), ('vip', 'ВИП'), ('proraba', 'Дом прораба'), ('aurora', 'Аврора'), ('domik', 'Домик')], default='standard', max_length=30, verbose_name='Класс комнаты'),
        ),
    ]
