# Generated by Django 5.2.3 on 2025-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('semi_lux', 'Полу-люкс'), ('lux', 'Люкс'), ('vip', 'ВИП'), ('proraba', 'Дом прораба'), ('aurora', 'Аврора'), ('domik', 'Домик')], max_length=20, verbose_name='Класс'),
        ),
    ]
