# Generated by Django 5.2.3 on 2025-06-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_room_room_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.CharField(blank=True, max_length=255, verbose_name='Удобства (через запятую)'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за сутки'),
        ),
        migrations.AddField(
            model_name='room',
            name='rooms_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество комнат'),
        ),
    ]
