# Generated by Django 5.2.3 on 2025-06-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_amenities_room_is_active_room_price_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Комментарии'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма оплаты'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Банковская карта'), ('transfer', 'Банковский перевод'), ('online', 'Онлайн оплата'), ('other', 'Другое')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачено'), ('partial', 'Частично оплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма'),
        ),
    ]
