# Generated by Django 5.2.3 on 2025-06-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_room_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.CharField(choices=[('standard', 'Стандарт'), ('lux', 'Люкс'), ('semi_lux', 'Полу-люкс'), ('vip', 'ВИП'), ('proraba', 'Дом прораба'), ('aurora', 'Аврора'), ('domik', 'Домик'), ('three_floor_lux', '3-х этажка люкс'), ('middle_vip_lux', 'Средний ВИП люкс'), ('pink', 'Розовый'), ('sklad', 'Склад'), ('other', 'Другое')], default='standard', max_length=40, verbose_name='Класс комнаты'),
        ),
    ]
