# Generated by Django 5.2.3 on 2025-06-27 13:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_comments_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='guest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='guest',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('vip', 'ВИП'), ('blacklist', 'Чёрный список')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='guest',
            name='total_spent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая сумма потраченная'),
        ),
        migrations.AddField(
            model_name='guest',
            name='visits_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество посещений'),
        ),
    ]
