# Generated by Django 5.2.3 on 2025-07-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_is_deleted_guest_is_deleted_room_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.DateTimeField(verbose_name='Дата и время заезда'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.DateTimeField(verbose_name='Дата и время выезда'),
        ),
    ]
