'use client';

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import { useTranslation } from 'react-i18next';
import Sidebar from '../components/Sidebar';
import { FaUserCircle } from 'react-icons/fa';
import { usePathname } from 'next/navigation';
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function Layout({ children }: { children: React.ReactNode }) {
  const { i18n } = useTranslation();
  const pathname = usePathname();
  const isAuthPage = pathname.startsWith('/login');

  const handleLogout = () => {
    if (typeof window !== 'undefined') {
      localStorage.removeItem('access');
      localStorage.removeItem('refresh');
      window.location.href = '/login';
    }
  };

  const changeLang = (lang: string) => {
    i18n.changeLanguage(lang);
  };

  return (
    <html lang="ru">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        {isAuthPage ? (
          <main>{children}</main>
        ) : (
          <div className="flex min-h-screen">
            <Sidebar onLogout={() => {}} />
            <div className="flex-1 flex flex-col ml-64 min-h-screen">
              <header className="bg-white shadow flex items-center px-8 py-4 h-16">
                <div className="ml-auto flex gap-4 items-center">
                  <button
                    onClick={() => changeLang('ru')}
                    className={`px-2 py-1 rounded flex items-center gap-1 text-sm font-semibold border ${i18n.language === 'ru' ? 'bg-blue-600 text-white border-blue-600' : 'bg-blue-50 text-blue-700 border-blue-100 hover:bg-blue-100'}`}
                  >
                    <Image src="/ru-flag.svg" alt="Русский" width={20} height={14} /> RU
                  </button>
                  <button
                    onClick={() => changeLang('ky')}
                    className={`px-2 py-1 rounded flex items-center gap-1 text-sm font-semibold border ${i18n.language === 'ky' ? 'bg-blue-600 text-white border-blue-600' : 'bg-blue-50 text-blue-700 border-blue-100 hover:bg-blue-100'}`}
                  >
                    <Image src="/ky-flag.svg" alt="Кыргызский" width={20} height={14} /> KY
                  </button>
                  <FaUserCircle size={28} className="text-gray-400" />
                  <button
                    onClick={handleLogout}
                    className="ml-2 px-4 py-2 rounded bg-red-100 hover:bg-red-200 text-red-700 font-semibold transition-all"
                  >
                    Выйти
                  </button>
                </div>
              </header>
              <main className="p-8">{children}</main>
            </div>
          </div>
        )}
      </body>
    </html>
  );
}
